---
name: Publish
# 'on':
#   push:
#     tags:
#       - '*'
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 1.0.1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: make clean deps package install
      - run: make publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_NON_INTERACTIVE: '1'